/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Nightmare Creatures II)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80096F58u
#define func_80096F58 BootEntry  /* alias */
